SERVICES:
  - name: service-1
    namespaces:
      - namespace-1
    forwardings:
      - protocol: http
        remote_port: 8080

  - name: service-2
    namespaces:
      - namespace-1
      - namespace-2
    forwardings:
      - protocol: grpc
        remote_port: 50051
        # local_port: 50052  if you want set specific port for forwarding.
